---
# Source: moonlay-ctp-chart/charts/cp-helm-charts/charts/cp-ksql-server/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: RELEASE-NAME-cp-ksql-server
  labels:
    app: cp-ksql-server
    chart: cp-ksql-server-0.1.0
    release: RELEASE-NAME
    heritage: Helm
spec:
  ports:
      - name: ksql-server
        port: 8088
  selector:
    app: cp-ksql-server
    release: RELEASE-NAME
