apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mdm-app-chart.fullname" . }}
  labels:
    {{- include "mdm-app-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mdm-app-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mdm-app-chart.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "mdm-app-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: Grpc__ServerUrl
              value: https://{{ include "mdm-grpc-chart.fullname" . }}
            - name: Kafka__Producer__bootstrap.servers
              value: {{ include "cp-kafka.fullname" . }}:9092
            - name: Kafka__SchemaRegistry__schema.registry.url
              value: {{ include "cp-schema-registry.fullname" . }}:8081
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
