apiVersion: v1
kind: Service
metadata:
  name: {{ include "mdm-grpc-chart.fullname" . }}
  labels:
    {{- include "mdm-grpc-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
    - port: {{ .Values.service.portTls }}
      targetPort: 443
      protocol: TCP
      name: https
  selector:
    {{- include "mdm-grpc-chart.selectorLabels" . | nindent 4 }}
