---
# Source: moonlay-ctp-chart/charts/cp-helm-charts/charts/cp-kafka-rest/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: RELEASE-NAME-cp-kafka-rest
  labels:
    app: cp-kafka-rest
    chart: cp-kafka-rest-0.1.0
    release: RELEASE-NAME
    heritage: Helm
spec:
  ports:
    - name: rest-proxy
      port: 8082
  selector:
    app: cp-kafka-rest
    release: RELEASE-NAME
