---
# Source: moonlay-ctp-chart/charts/cp-helm-charts/charts/cp-kafka-connect/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: RELEASE-NAME-cp-kafka-connect
  labels:
    app: cp-kafka-connect
    chart: cp-kafka-connect-0.1.0
    release: RELEASE-NAME
    heritage: Helm
spec:
  ports:
    - name: kafka-connect
      port: 8083
  selector:
    app: cp-kafka-connect
    release: RELEASE-NAME
